framework:
  form: ~
  secret: XXXXXXX
  csrf_protection: ~
  router:        { resource: "%kernel.root_dir%/config/routing.yml" }
  validation:    { enable_annotations: true, strict_email: true}
  templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
  session:
    # handler_id set to null will use default session handler from php.ini
    handler_id:  ~
twig:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%

doctrine_mongodb:
  connections:
    default:
      server: mongodb://localhost:27017
      options: {}
  default_database: livechat
  auto_generate_hydrator_classes: true
  document_managers:
    default:
      auto_mapping: true
      metadata_cache_driver: array # array, apc, xcache, memcache
      mappings:
        SGLiveChatBundle: ~

#swiftmailer:
#  transport: "%mailer_transport%"
#  host:      "%mailer_host%"
#  username:  "%mailer_user%"
#  password:  "%mailer_password%"
#  spool:     { type: memory }

sg_live_chat:
#  cache_engine: mongo # apc by default
