homepage:
  path:  /
  defaults: { _controller: SGLiveChatBundle:Default:index }

# -- Live Chat -----------------------------------------------------------------

sglc_chat_homepage:
    path:  /sglivechat
    defaults: { _controller: SGLiveChatBundle:Chat:index }

sglc_chat_invite:
  path: /sglivechat/{sessId}/invite
  defaults: { _controller: SGLiveChatBundle:Chat:invite }

sglc_chat_invite_accept:
  path: /sglivechat/{id}/invite/accept
  defaults: { _controller: SGLiveChatBundle:Chat:acceptInvite }

sglc_chat_invite_reject:
  path: /sglivechat/{id}/invite/reject
  defaults: { _controller: SGLiveChatBundle:Chat:rejectInvite }

sglc_chat_load:
  path: /sglivechat/{id}/load
  defaults: { _controller: SGLiveChatBundle:Chat:load }

sglc_chat_accept:
  path: /sglivechat/{id}/accept
  defaults: { _controller: SGLiveChatBundle:Chat:accept }

sglc_chat_reject:
  path: /sglivechat/{id}/reject/
  defaults: { _controller: SGLiveChatBundle:Chat:reject }
  
sglc_chat_user_action:
  path: /sglivechat/{id}/user/action/{action}
  defaults: { _controller: SGLiveChatBundle:Chat:userAction }

sglc_chat_done:
  path: /sglivechat/{id}/done
  defaults: { _controller: SGLiveChatBundle:Chat:done }

sglc_chat_send:
  path: /sglivechat/{id}/send
  defaults: { _controller: SGLiveChatBundle:Chat:send }
  requirements: { _method: post }

sglc_chat_messages:
  path: /sglivechat/{id}/messages.{_format}
  defaults: { _controller: SGLiveChatBundle:Chat:messages, _format: html }
  requirements: { _method: get }
  
sglc_chat_status:
  path: /sglivechat/status
  defaults: { _controller: SGLiveChatBundle:Chat:status }
  requirements: { _method: get }


# -- Tracker -------------------------------------------------------------------

sglc_track_index:
  path: /js/sglivechat-tracker
  defaults: { _controller: SGLiveChatBundle:Track:index }
  requirements: { _method: get }

sglc_track_updater:
  path: /js/sglivechat-tracker/update
  defaults: { _controller: SGLiveChatBundle:Track:update }

sglc_track_reset:
  path: /js/sglivechat-tracker/reset
  defaults: { _controller: SGLiveChatBundle:Track:reset }
sglc_track_status:
  path: /js/sglivechat-tracker/status.{_format}
  defaults: { _controller: SGLiveChatBundle:Track:status, _format: html }

# -- Admin ---------------------------------------------------------------------

sglc_admin_index:
  path: /admin/sglivechat
  defaults: { _controller: SGLiveChatBundle:Admin:index }
  requirements: { _method: get }

sglc_admin_logout:
  path: /admin/sglivechat/logout
  defaults: { _controller: SGLiveChatBundle:Admin:logout }
  requirements: { _method: get }

#sglc_admin_login:
#  path: /admin/sglivechat/login
#  defaults: { _controller: SGLiveChatBundle:Admin:login }


#sglc_admin_check_login:
#  path: /admin/sglivechat/login/check
#  defaults: { _controller: SGLiveChatBundle:Admin:checkLogin }
  
_security_login:
  path: /admin/sglivechat/login
  defaults: { _controller: SGLiveChatBundle:Admin:login }

_security_check:
  path: /admin/sglivechat/login/check
  defaults: { _controller: SGLiveChatBundle:Admin:checkLogin }
  requirements: { _method: post }

sglc_admin_operator:
  path: /admin/sglivechat/operator
  defaults: { _controller: SGLiveChatBundle:Admin:operator }

sglc_admin_operator_departments:
  path: /admin/sglivechat/operator/departments
  defaults: { _controller: SGLiveChatBundle:Admin:operatorDepartments }

sglc_admin_operator_department:
  path: /admin/sglivechat/operator/department
  defaults: { _controller: SGLiveChatBundle:Admin:operatorDepartment }
  

sglc_admin_operator_department_edit:
  path: /admin/sglivechat/operator/department/{id}
  defaults: { _controller: SGLiveChatBundle:Admin:operatorDepartment }

sglc_admin_operator_edit:
  path: /admin/sglivechat/operator/{id}
  defaults: { _controller: SGLiveChatBundle:Admin:operator }

sglc_admin_operators:
  path: /admin/sglivechat/operators
  defaults: { _controller: SGLiveChatBundle:Admin:operators }

sglc_admin_console_sessions:
  path: /admin/sglivechat/console/sessions
  defaults: { _controller: SGLiveChatBundle:Admin:sessions }

sglc_admin_console_requested_chats:
  path: /admin/sglivechat/console/requested-chats.{_format}
  defaults: { _controller: SGLiveChatBundle:Admin:requestedChats, _format: html }

sglc_admin_console_current_visits:
  path: /admin/sglivechat/console/current-visits.{_format}
  defaults: { _controller: SGLiveChatBundle:Admin:currentVisits, _format: html }

sglc_admin_console_sessions_service:
  path: /admin/sglivechat/console/sessions-service.json
  defaults: { _controller: SGLiveChatBundle:Admin:sessionsService }

sglc_admin_console_close:
  path: /admin/sglivechat/console/close/{id}
  defaults: { _controller: SGLiveChatBundle:Admin:closeChat }